import asyncio
from sqlalchemy import select
from database import AsyncSessionLocal, engine
from models import Product


async def create_and_read():
    async with AsyncSessionLocal() as session:
        print("Creating New Product...")

        new_product = Product(name="Gaming Laptop", price=1500.00, stock=5)

        session.add(new_product)

        await session.commit()
        await session.refresh(new_product)

        print(f"Created Product: {new_product}")
        print(f"ID:{new_product.id} (Generated by DB)")

        print("\nReading from database")

        statement = select(Product).where(Product.name == "Gaming Laptop")

        result = await session.execute(statement)

        fetched_product = result.scalar_one_or_none()

        print(f"Fetched from DB: {fetched_product}")
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(create_and_read())
